//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_OS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ELETRODOMÉSTICOS OURINHENSE")]
        public string nomeCliente {
            get {
                return ((string)(this["nomeCliente"]));
            }
            set {
                this["nomeCliente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ORLANDO SILVA NETO ME")]
        public string razaoSocial {
            get {
                return ((string)(this["razaoSocial"]));
            }
            set {
                this["razaoSocial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Peças e serviços em Eletrodomésticos em Geral - Ferramentas Elétricas - Microonda" +
            "s - Posto Autorizado -  Arno - Black&Decker - Dewalt - Layr - Taiff - GA.MA - Ne" +
            "rdelli")]
        public string descricao {
            get {
                return ((string)(this["descricao"]));
            }
            set {
                this["descricao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rua Expedicionários no 163 - Centro - CEP 19900-041 - Ourinhos - SP")]
        public string endereco {
            get {
                return ((string)(this["endereco"]));
            }
            set {
                this["endereco"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(14) 3322 - 3662")]
        public string tel1 {
            get {
                return ((string)(this["tel1"]));
            }
            set {
                this["tel1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(14) 3026 - 3662")]
        public string tel2 {
            get {
                return ((string)(this["tel2"]));
            }
            set {
                this["tel2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eletroourinhense@terra.com.br")]
        public string email {
            get {
                return ((string)(this["email"]));
            }
            set {
                this["email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string adicional1 {
            get {
                return ((string)(this["adicional1"]));
            }
            set {
                this["adicional1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string adicional2 {
            get {
                return ((string)(this["adicional2"]));
            }
            set {
                this["adicional2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string adicional3 {
            get {
                return ((string)(this["adicional3"]));
            }
            set {
                this["adicional3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usuarioPadrao {
            get {
                return ((string)(this["usuarioPadrao"]));
            }
            set {
                this["usuarioPadrao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string senhaPadrao {
            get {
                return ((string)(this["senhaPadrao"]));
            }
            set {
                this["senhaPadrao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool salvarUsuarioChecado {
            get {
                return ((bool)(this["salvarUsuarioChecado"]));
            }
            set {
                this["salvarUsuarioChecado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection listaUsuariosValidosSalvos {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["listaUsuariosValidosSalvos"]));
            }
            set {
                this["listaUsuariosValidosSalvos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font fontTitulo {
            get {
                return ((global::System.Drawing.Font)(this["fontTitulo"]));
            }
            set {
                this["fontTitulo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font fontCabecalho {
            get {
                return ((global::System.Drawing.Font)(this["fontCabecalho"]));
            }
            set {
                this["fontCabecalho"] = value;
            }
        }
    }
}
